In [9]:
#Display the csv table
import pandas as pd
df = pd.read_csv('weekly_logins.csv')
df

,User Name,Slack Integration,Most Used Page,Had Free Trial,User MRR,Weekly Logins,Company Name,Industry,Company Size,Territory,Sales Call in Trial,Zendesk Integration,Salesforce Integration,Gmail Integration,Most common referrer,Most common IP,Sales Touches to Close,Used Admin Panel,Has Issued Support Request
0,Nilsa Harmon,No,/home,No,39,2,HP,Technology,>$10B,West,No,Yes,No,Yes,hotels.com,165.227.215.62,5,No,No
1,Joni Catano,No,/tool/storyboard,No,39,6,HP,Technology,>$10B,West,No,Yes,Yes,No,hotels.com,159.203.166.41,16,No,Yes
2,Emmett Jeffries,Yes,/tool/search,Yes,169,3,HP,Technology,>$10B,West,Yes,No,Yes,No,hotels.com,159.203.166.41,4,No,Yes
3,Dian Boisse,No,/tool/storyboard,No,39,2,HP,Technology,>$10B,West,No,Yes,No,No,zoom.com,162.243.108.129,15,No,Yes
4,Barbara Herrera,No,/tool/storyboard,No,1299,7,HP,Technology,>$10B,West,No,No,Yes,No,/mail.google.com,159.203.166.41,5,No,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1713,Tammy Martin,No,/tool/storyboard,No,39,3,Zoom Video Communications,Technology,$100M - $500M,West,No,No,Yes,No,/quora,142.93.8.33,14,Yes,No
1714,Irene Scott,No,/tool/storyboard,No,39,4,Zoom Video Communications,Technology,$100M - $500M,West,Yes,No,Yes,Yes,/google.com,165.227.215.62,13,No,Yes
1715,Candelaria Hill,No,/home,No,169,1,Zoom Video Communications,Technology,$100M - $500M,West,No,No,Yes,Yes,zoom.com,192.200.200.99,14,No,No
1716,Loretta Sanders,Yes,/tool/storyboard,Yes,169,10,Zoom Video Communications,Technology,$100M - $500M,West,No,No,No,No,/tripadvisor.com,67.205.132.241,13,Yes,No
1717,Derek Crumm,No,/tool/storyboard,No,169,3,Zoom Video Communications,Technology,$100M - $500M,West,No,No,No,Yes,/google.com,162.243.107.120,10,No,No

In [82]:
#Most Used Page x Weekly Logins
df = df.groupby(['Most Used Page'])
df.sum()

                   User MRR  Weekly Logins  Sales Touches to Close
Most Used Page
/dashboard            12799            255                     630
/home                 15072            249                     591
/login                14306            234                     610
/tool/build_query     12578            253                     623
/tool/search          15553            297                     631
/tool/storyboard     294534           9133                   13974

In [90]:
#Company Name x Weekly Logins
df = df.groupby(['Company Name'])
df.sum()

                               User MRR  Weekly Logins  Sales Touches to Close
Company Name
HP                                14721            413                     675
Huron Consulting Group             7498            274                     452
Hushmail                          17737            491                     882
InVision                          10889            324                     569
LiveRamp                          11241            413                     673
Lucky Brand                       15047            448                     736
Lush                               3574            160                     241
One Legal                          2405            200                     268
Siemon                            30132            744                    1173
SpaceX                            17958            583                     950
Stupp Bros                        33520            533                    1026
TaxSlayer, LLC                    20180            597                     995
Twilio                            17958            560                     922
US Soccer Federation              27197            867                    1232
Uniform Law Commission             8357            415                     727
Veritext                           3586             91                     153
Visa                              32146            774                    1479
Wal-Mart Stores                   11903            380                     593
Whitesell Corporation              1365            101                     149
Worldsource Wealth Management     31873            895                    1292
Yahoo! Inc.                       11864            412                     593
Zendesk                           21140            507                     785
Zoom Video Communications         12551            239                     494

In [72]:
#Most Common Referrer x Weekly Logins
df = df.groupby(['Most common referrer'])
df.sum()

                      User MRR  Weekly Logins  Sales Touches to Close
Most common referrer
/facebook.com            44218           1265                    2077
/google.com              40205           1360                    2145
/mail.google.com         49168           1408                    2276
/quora                   43622           1274                    2235
/slack.com               50649           1351                    2208
/tripadvisor.com         42166           1279                    2081
hotels.com               51818           1303                    2034
zoom.com                 42996           1181                    2003

In [99]:
#Most common IP x Weekly Logins
df = df.groupby(['Most common IP'])
df.sum()

                 User MRR  Weekly Logins  Sales Touches to Close
Most common IP
102.129.249.120     20893            470                     741
134.209.44.228      19582            540                     826
138.197.222.35      19607            549                     823
138.68.240.218      14594            570                    1023
138.68.41.90        16204            591                     936
142.93.8.33         21595            501                     849
159.203.166.41      19126            541                     881
162.243.107.120     16904            433                     802
162.243.108.129     16035            491                     810
162.243.108.141     13280            420                     624
162.243.108.161     23843            625                     920
165.227.215.62      14892            514                     890
174.138.54.49       17178            462                     828
191.96.42.80        21790            511                     877
192.200.200.99      24232            647                     967
198.199.120.102      9111            493                     773
34.87.141.207       19075            525                     922
45.55.9.218         11060            398                     765
67.205.132.241      22752            559                     888
72.35.40.34         23089            581                     914

In [79]:
#Industry x Company Size x Weekly Logins
df = df.groupby(['Industry','Company Size'])
df.sum()

                                     User MRR  Weekly Logins  \
Industry              Company Size
Consumer Products     $100M - $500M     18621            608
Finance               $100M - $500M     31873            895
Hospitality           <$100M            30783            958
Legal Services        <$100M            10762            615
Manufacturing         $100M - $500M     63652           1277
                      <$100M             1365            101
Other                 >$10B             11903            380
Professional Services $500M - $1B        7498            274
Technology            $100M - $500M     70376           2027
                      $1B - $10B        29822            995
                      $500M - $1B       21140            507
                      <$100M            20180            597
                      >$10B             46867           1187

                                     Sales Touches to Close
Industry              Company Size
Consumer Products     $100M - $500M                     977
Finance               $100M - $500M                    1292
Hospitality           <$100M                           1385
Legal Services        <$100M                            995
Manufacturing         $100M - $500M                    2199
                      <$100M                            149
Other                 >$10B                             593
Professional Services $500M - $1B                       452
Technology            $100M - $500M                    3540
                      $1B - $10B                       1543
                      $500M - $1B                       785
                      <$100M                            995
                      >$10B                            2154

In [85]:
#Industry x Territory x Weekly Logins
df = df.groupby(['Industry','Territory'])
df.sum()

                                 User MRR  Weekly Logins  \
Industry              Territory
Consumer Products     East           3574            160
                      West          15047            448
Finance               East          31873            895
Hospitality           Midwest       30783            958
Legal Services        East           2405            200
                      Midwest        8357            415
Manufacturing         Midwest       65017           1378
Other                 Midwest       11903            380
Professional Services East           7498            274
Technology            East          31069            921
                      West         157316           4392

                                 Sales Touches to Close
Industry              Territory
Consumer Products     East                          241
                      West                          736
Finance               East                         1292
Hospitality           Midwest                      1385
Legal Services        East                          268
                      Midwest                       727
Manufacturing         Midwest                      2348
Other                 Midwest                       593
Professional Services East                          452
Technology            East                         1564
                      West                         7453

In [8]:
df = df.groupby(['Industry'])
df.count()

,User Name,Slack Integration,Most Used Page,Had Free Trial,User MRR,Weekly Logins,Company Name,Company Size,Territory,Sales Call in Trial,Zendesk Integration,Salesforce Integration,Gmail Integration,Most common referrer,Most common IP,Sales Touches to Close,Used Admin Panel,Has Issued Support Request
Industry,,,,,,,,,,,,,,,,,,
Consumer Products,99,99,99,99,99,99,99,99,99,99,99,99,99,99,99,99,99,99
Finance,137,137,137,137,137,137,137,137,137,137,137,137,137,137,137,137,137,137
Hospitality,147,147,147,147,147,147,147,147,147,147,147,147,147,147,147,147,147,147
Legal Services,98,98,98,98,98,98,98,98,98,98,98,98,98,98,98,98,98,98
Manufacturing,233,233,233,233,233,233,233,233,233,233,233,233,233,233,233,233,233,233
Other,67,67,67,67,67,67,67,67,67,67,67,67,67,67,67,67,67,67
Professional Services,42,42,42,42,42,42,42,42,42,42,42,42,42,42,42,42,42,42
Technology,895,895,895,895,895,895,895,895,895,895,895,895,895,895,895,895,895,895

In [10]:
df = df.groupby(['Territory'])
df.count()

,User Name,Slack Integration,Most Used Page,Had Free Trial,User MRR,Weekly Logins,Company Name,Industry,Company Size,Sales Call in Trial,Zendesk Integration,Salesforce Integration,Gmail Integration,Most common referrer,Most common IP,Sales Touches to Close,Used Admin Panel,Has Issued Support Request
Territory,,,,,,,,,,,,,,,,,,
East,381,381,381,381,381,381,381,381,381,381,381,381,381,381,381,381,381,381
Midwest,520,520,520,520,520,520,520,520,520,520,520,520,520,520,520,520,520,520
West,817,817,817,817,817,817,817,817,817,817,817,817,817,817,817,817,817,817

In [97]:
#Referrer x Company Name x Weekly Logins
df = df.groupby(['Company Name','Most common referrer'])
pd.set_option('display.max_rows', None)
df.sum()

                                                    User MRR  Weekly Logins  \
Company Name                  Most common referrer
HP                            /facebook.com             2378             70
                              /google.com                156             20
                              /mail.google.com          4261             56
                              /quora                      78              4
                              /slack.com                3495            122
                              /tripadvisor.com           741             33
                              hotels.com                 741             57
                              zoom.com                  2871             51
Huron Consulting Group        /facebook.com             1962             37
                              /google.com                416             31
                              /mail.google.com           208             21
                              /quora                     416             35
                              /slack.com                1793             41
                              /tripadvisor.com           507             28
                              hotels.com                 416             17
                              zoom.com                  1780             64
Hushmail                      /facebook.com             1533             37
                              /google.com               1793             41
                              /mail.google.com          1417            102
                              /quora                    2768             63
                              /slack.com                2378             79
                              /tripadvisor.com          4469             59
                              hotels.com                1131             50
                              zoom.com                  2248             60
InVision                      /facebook.com             1546             33
                              /google.com               1715             35
                              /mail.google.com          2040             72
                              /quora                    1923             42
                              /slack.com                1624             40
                              /tripadvisor.com           663             28
                              hotels.com                 754             42
                              zoom.com                   624             32
LiveRamp                      /facebook.com             1118             72
                              /google.com               3092             35
                              /mail.google.com           663             34
                              /quora                     702             59
                              /slack.com                2378             78
                              /tripadvisor.com          1884             47
                              hotels.com                 416             15
                              zoom.com                   988             73
Lucky Brand                   /facebook.com              455             27
                              /google.com                403             42
                              /mail.google.com          1040             67
                              /quora                    2170             45
                              /slack.com                2131             64
                              /tripadvisor.com          4599             83
                              hotels.com                3508             85
                              zoom.com                   741             35
Lush                          /facebook.com              208              8
                              /google.com                117             17
                              /mail.google.com           416             14
                              /quora                    1715             36
                              /slack.com                 286             37
                              /tripadvisor.com           208              7
                              hotels.com                 455             35
                              zoom.com                   169              6
One Legal                     /facebook.com               39              5
                              /google.com                 39              7
                              /mail.google.com           624             51
                              /quora                     416             24
                              /slack.com                 117             24
                              /tripadvisor.com           663             62
                              hotels.com                 169              6
                              zoom.com                   338             21
Siemon                        /facebook.com             2638             67
                              /google.com               3469             72
                              /mail.google.com          2963            111
                              /quora                    4638             60
                              /slack.com                2937             72
                              /tripadvisor.com          2625             89
                              hotels.com                7107            170
                              zoom.com                  3755            103
SpaceX                        /facebook.com             3222             50
                              /google.com               5353            119
                              /mail.google.com          3417             68
                              /quora                    2963            126
                              /slack.com                1326             85
                              /tripadvisor.com           273             45
                              hotels.com                 611             43
                              zoom.com                   793             47
Stupp Bros                    /facebook.com             4807             76
                              /google.com               6275             99
                              /mail.google.com          3183             41
                              /quora                    6626             62
                              /slack.com                3287             69
                              /tripadvisor.com          2326             57
                              hotels.com                3638             68
                              zoom.com                  3378             61
TaxSlayer, LLC                /facebook.com             2300             64
                              /google.com               1677             89
                              /mail.google.com          4677             85
                              /quora                    2313             82
                              /slack.com                3339             69
                              /tripadvisor.com           572             47
                              hotels.com                3560             54
                              zoom.com                  1742            107
Twilio                        /facebook.com             2417             63
                              /google.com               2456             82
                              /mail.google.com          3456            107
                              /quora                    2378             83
                              /slack.com                 247              9
                              /tripadvisor.com          1209             71
                              hotels.com                5132             99
                              zoom.com                   663             46
US Soccer Federation          /facebook.com             2443            114
                              /google.com               2339             87
                              /mail.google.com          4639            128
                              /quora                    1261             40
                              /slack.com                5977            144
                              /tripadvisor.com          1988             76
                              hotels.com                3158            154
                              zoom.com                  5392            124
Uniform Law Commission        /facebook.com             1741             64
                              /google.com                780             62
                              /mail.google.com          2339             43
                              /quora                     897             79
                              /slack.com                 416             33
                              /tripadvisor.com           650             56
                              hotels.com                 871             43
                              zoom.com                   663             35
Veritext                      /facebook.com             1377             26
                              /google.com                208             18
                              /mail.google.com            39              6
                              /slack.com                1507             20
                              /tripadvisor.com           169              1
                              hotels.com                  78              8
                              zoom.com                   208             12
Visa                          /facebook.com             4457            154
                              /google.com               2275            120
                              /mail.google.com          5262            125
                              /quora                    2872            100
                              /slack.com                3625             61
                              /tripadvisor.com          5639            104
                              hotels.com                3430             65
                              zoom.com                  4586             45
Wal-Mart Stores               /facebook.com             2040             59
                              /google.com               1248             75
                              /mail.google.com          1923             44
                              /quora                     624             28
                              /slack.com                 741             43
                              /tripadvisor.com           611             53
                              hotels.com                 533             39
                              zoom.com                  4183             39
Whitesell Corporation         /facebook.com               39              4
                              /google.com                208              7
                              /mail.google.com            78             13
                              /quora                     585             32
                              /tripadvisor.com            39              7
                              hotels.com                  39             15
                              zoom.com                   377             23
Worldsource Wealth Management /facebook.com             2742            109
                              /google.com               1222            113
                              /mail.google.com          4755            107
                              /quora                    3872            135
                              /slack.com                3768             76
                              /tripadvisor.com          5094            169
                              hotels.com                5782            100
                              zoom.com                  4638             86
Yahoo! Inc.                   /facebook.com              572             36
                              /google.com                702             50
                              /mail.google.com           741             45
                              /quora                    1832             56
                              /slack.com                1131             51
                              /tripadvisor.com          3092             67
                              hotels.com                3261             74
                              zoom.com                   533             33
Zendesk                       /facebook.com             2508             72
                              /google.com               3768             90
                              /mail.google.com           624             49
                              /quora                    2209             58
                              /slack.com                2326             90
                              /tripadvisor.com          3690             55
                              hotels.com                4183             44
                              zoom.com                  1832             49
Zoom Video Communications     /facebook.com             1676             18
                              /google.com                494             49
                              /mail.google.com           403             19
                              /quora                     364             25
                              /slack.com                5820             44
                              /tripadvisor.com           455             35
                              hotels.com                2845             20
                              zoom.com                   494             29

                                                    Sales Touches to Close
Company Name                  Most common referrer
HP                            /facebook.com                            134
                              /google.com                               31
                              /mail.google.com                          83
                              /quora                                    11
                              /slack.com                               148
                              /tripadvisor.com                          83
                              hotels.com                               105
                              zoom.com                                  80
Huron Consulting Group        /facebook.com                             86
                              /google.com                               61
                              /mail.google.com                          20
                              /quora                                    39
                              /slack.com                                65
                              /tripadvisor.com                          31
                              hotels.com                                57
                              zoom.com                                  93
Hushmail                      /facebook.com                             74
                              /google.com                               96
                              /mail.google.com                         138
                              /quora                                   116
                              /slack.com                               136
                              /tripadvisor.com                         121
                              hotels.com                                80
                              zoom.com                                 121
InVision                      /facebook.com                             44
                              /google.com                               58
                              /mail.google.com                         115
                              /quora                                    85
                              /slack.com                                65
                              /tripadvisor.com                          66
                              hotels.com                                69
                              zoom.com                                  67
LiveRamp                      /facebook.com                            130
                              /google.com                               69
                              /mail.google.com                          68
                              /quora                                    79
                              /slack.com                               119
                              /tripadvisor.com                          65
                              hotels.com                                31
                              zoom.com                                 112
Lucky Brand                   /facebook.com                             54
                              /google.com                               48
                              /mail.google.com                         123
                              /quora                                   100
                              /slack.com                                73
                              /tripadvisor.com                          96
                              hotels.com                               136
                              zoom.com                                 106
Lush                          /facebook.com                             14
                              /google.com                               36
                              /mail.google.com                          30
                              /quora                                    40
                              /slack.com                                45
                              /tripadvisor.com                          26
                              hotels.com                                37
                              zoom.com                                  13
One Legal                     /facebook.com                             14
                              /google.com                                6
                              /mail.google.com                          64
                              /quora                                    54
                              /slack.com                                23
                              /tripadvisor.com                          75
                              hotels.com                                 9
                              zoom.com                                  23
Siemon                        /facebook.com                             86
                              /google.com                              113
                              /mail.google.com                         194
                              /quora                                   121
                              /slack.com                               117
                              /tripadvisor.com                         171
                              hotels.com                               222
                              zoom.com                                 149
SpaceX                        /facebook.com                             79
                              /google.com                              173
                              /mail.google.com                         121
                              /quora                                   195
                              /slack.com                               130
                              /tripadvisor.com                          69

In [6]:
#Territory x Weekly Logins
df = df.groupby(['Territory'])
df.sum()

           User MRR  Weekly Logins  Sales Touches to Close
Territory
East          76419           2450                    3817
Midwest      116060           3131                    5053
West         172363           4840                    8189

# Summary

##### There are a few notable trends I would like to point out with this data. 
    1. Most used page x Weekly logins: When we aggregate the data by most used page, we see that the /tool/storyboard function leads to a significantly greater amount of weekly login among users than any other pathway.
    2. Industry x Company size x Weekly logins: When we group the data first by industry and then by company size, we see that users in tech have the highest amount of weekly logins, particularly those from companies sized $100M-$500M. Also notable are users from technology companies sized over $10B and those from manufacturing companies sized $100M-$500M. 
    3. Industry x Territory x Weekly logins: Lastly, users in the technology industry who have high engagement with Umba's platform primarily come from the Western territory.